# Generated by Django 2.2.7 on 2019-12-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(help_text='Longitude')),
                ('lat', models.FloatField(help_text='Latitude')),
                ('squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=20)),
                ('shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='AM', max_length=2)),
                ('date', models.DateField(help_text='Date')),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('other', 'Other')], default='other', max_length=20)),
                ('pri_fur_color', models.CharField(choices=[('gray', 'Gray'), ('cinnamon', 'Cinnamon'), ('black', 'Black'), ('other', 'Other')], default='other', help_text='Primary Fur Color', max_length=20)),
                ('location', models.CharField(choices=[('ground plane', 'Ground Plane'), ('above ground', 'Above Ground'), ('other', 'Other')], default='other', max_length=50)),
                ('specific_location', models.CharField(help_text='Specific location', max_length=1000)),
                ('running', models.BooleanField(default=False, help_text='Squirrel was seen running or not')),
                ('chasing', models.BooleanField(default=False, help_text='Squirrel was seen chasing another squirrel or not')),
                ('climbing', models.BooleanField(default=False, help_text='Squirrel was seen climbing a tree or not')),
                ('eating', models.BooleanField(default=False, help_text='Squirrel was seen eating or not')),
                ('foraging', models.BooleanField(default=False, help_text='Squirrel was seen foraging for food or not')),
                ('other_activities', models.CharField(help_text='Other behaviors of squirrels', max_length=1000)),
                ('kuks', models.BooleanField(default=False, help_text='Squirrel was heard kukking or not (a chirpy vocal communication)')),
                ('quaas', models.BooleanField(default=False, help_text='Squirrel was heard Quaaing or not (an elongated vocal communication)')),
                ('moans', models.BooleanField(default=False, help_text='Squirrel was heard Moaning or not (a high-pitched vocal communication)')),
                ('tail_flags', models.BooleanField(default=False, help_text='Squirrel was seen flaging its tail or not')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Squirrel was seen twitching its tail or not')),
                ('approaches', models.BooleanField(default=False, help_text='Squirrel was seen approaching human or not')),
                ('indifferent', models.BooleanField(default=False, help_text='Squirrel was indifferent to human presence or not')),
                ('runs_from', models.BooleanField(default=False, help_text='Squirrel was seen running from humans or not')),
            ],
        ),
    ]
