# Generated by Django 2.2.7 on 2019-12-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('adult', 'adult'), ('juvenile', 'juvenile'), ('other', 'other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(choices=[('ground plane', 'ground plane'), ('above ground', 'above ground'), ('other', 'other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='pri_fur_color',
            field=models.CharField(choices=[('gray', 'gray'), ('cinnamon', 'cinnamon'), ('black', 'black'), ('other', 'other')], default='other', help_text='Primary Fur Color', max_length=20),
        ),
    ]
